export const page = [
    { value: 'home', label: "Home" },
    { value: 'product-list', label: "Product List" },
    { value: 'product-details', label: "Product Details" },
    { value: 'cart', label: "Cart" },
    { value: 'wishlist', label: "Wishlist" },
    { value: 'login', label: "Login" },
    { value: 'register', label: "Register" },
    { value: 'forgot-password', label: "Forgot Password" },
    { value: 'collections', label: "Collections" },
    { value: 'collections-brand', label: "Collections Brand" },
    { value: 'collections-category', label: "Collections Category" },
    { value: 'checkout', label: "Checkout" },
    { value: 'orders', label: "Orders" },
    { value: 'orders-details', label: "Orders Details" },
    { value: 'orders-success', label: "Orders Success" },
    { value: 'orders-failed', label: "Orders Failed" },
    { value: 'orders-return', label: "Orders Return" },
]

export const pageReference = [
    { value: 'header', label: "Header" },
    { value: 'top', label: "Top" },
    { value: 'top-left', label: "Top Left" },
    { value: 'top-right', label: "Top Right" },
    { value: 'top-center', label: "Top Center" },
    { value: 'top-gap', label: "Top Gap" },
    { value: 'top-bottom', label: "Top Bottom" },
    { value: 'top-middle', label: "Top Middle" },
    { value: 'middle', label: "Middle" },
    { value: 'middle-top', label: "Middle Top" },
    { value: 'middle-left', label: "Middle Left" },
    { value: 'middle-right', label: "Middle Right" },
    { value: 'middle-center', label: "Middle Center" },
    { value: 'middle-gap', label: "Middle Gap" },
    { value: 'middle-bottom', label: "Middle Bottom" },
    { value: 'bottom', label: "Bottom" },
    { value: 'bottom-top', label: "Bottom Top" },
    { value: 'bottom-left', label: "Bottom Left" },
    { value: 'bottom-right', label: "Bottom Right" },
    { value: 'bottom-center', label: "Bottom Center" },
    { value: 'bottom-middle', label: "Bottom Middle" },
    { value: 'bottom-gap', label: "Bottom Gap" },
    { value: 'footer', label: "Footer" },
    { value: 'footer-top', label: "Footer Top" },
    { value: 'footer-top-center', label: "Footer Top Center" },
    { value: 'footer-left', label: "Footer Left" },
    { value: 'footer-right', label: "Footer Right" },
    { value: 'footer-center', label: "Footer Center" },
    { value: 'footer-gap', label: "Footer Gap" },
    { value: 'footer-bottom', label: "Footer Bottom" },
    { value: 'footer-bottom-bottom', label: "Footer Bottom Bottom" },
    { value: 'sidebar-left', label: "Sidebar Left" },
    { value: 'sidebar-right', label: "Sidebar Right" }
];
